version: '2.2'

services:
  sqlserver:
    image: dog830228/sqlserverdemo:latest
    hostname: sqlsever
    build:
      context: SqlServer/
    ports:
      - "1433:1433"
    restart: always
    networks:
      - netcore
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'test.123'
      MSSQL_PID: 'Standard'

  web:
    image: dog830228/netcoresample:1.0
    build:
      context: NetCore/
      args:
        VERSION: 3.1
    ports:
      - "5000:5000"
    restart: always
    environment:
      DBConnection: 'Data Source=sqlserver;Initial Catalog=AdventureWorksDW2017;User ID=sa;Password=test.123;'
    networks:
      - netcore
    depends_on:
      - sqlserver

networks:
  netcore:
    driver: bridge
