version: '2.2'

services:
  grafana:
    image: grafana/grafana
    hostname: grafanaserver
    volumes:
      - "D:/grafana-storage:/var/lib/grafana"
    ports:
      - "3000:3000"
    expose:
      - "3000"
    restart: always
    networks:
      - grafananet
    depends_on:
      - telegraf

  influxdb:
    image: influxdb:1.8.6
    hostname: influxdb
    volumes:
      - "D:/InfluxDB:/var/lib/influxdb"
    ports:
      - "8086:8086"
    restart: always
    networks:
      - grafananet

  telegraf:
    image: telegraf:latest
    hostname: telegraf
    volumes:
      - "D:/telegraf.conf:/etc/telegraf/telegraf.conf"
    restart: always
    networks:
      - grafananet
    depends_on:
      - influxdb

networks:
  grafananet:
    driver: bridge
