version: '3.8'
services:
  oracle.xe:
    image: gvenzl/oracle-xe
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=test.123
    container_name: oracle-server
  ora2pg:
    container_name: ora2pg
    environment:
      CONFIG_LOCATION: "/config/ora2pg.conf"
      OUTPUT_LOCATION: "/data"
      ORA_HOST: "dbi:Oracle:host=oracle.xe;sid=SIDNAME;port=1521"
      ORA_USER: "system"
      ORA_PWD: "test.123"
    #command: ora2pg -t SHOW_VERSION -c /config/ora2pg.conf
    command: tail -f /dev/null
    volumes:
      - './config:/config'
      - './data:/data'
    image: georgmoser/ora2pg
  # vm-ubuntu:
  #   container_name: ubuntu
  #   image: ubuntu:22.04
  #   command: tail -f /dev/null

